### ISSUE TITLE
 数据库连接失败，请检查是否填写正确或联系数据库管理员

### ISSUE THREAD

**Issue by KingBridgeSS** [dgtmtx/nodercms#53]
![image](https://user-images.githubusercontent.com/93264909/203296248-16bc5aa6-f7a7-4a18-a39e-72d01e3195df.png)

```
[2022-11-22 18:52:57.070] [INFO] system - 正在监听 port 3000
[2022-11-22 18:53:00.106] [ERROR] console - (node:178720) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
(Use `node --trace-deprecation ...` to show where the warning was created)
[2022-11-22 18:53:00.116] [WARN] console - Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
[2022-11-22 18:53:00.122] [ERROR] access - PUT /api/install/test-database
[2022-11-22 18:53:00.122] [ERROR] console - (node:178720) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[2022-11-22 18:53:00.135] [WARN] console - Unhandled rejection MongoError: Authentication failed.
    at Function.MongoError.create (G:\workspace\realworld\cms\nodercms\nodercms\node_modules\mongoose\node_modules\mongodb-core\lib\error.js:31:11)
    at G:\workspace\realworld\cms\nodercms\nodercms\node_modules\mongoose\node_modules\mongodb-core\lib\connection\pool.js:497:72
    at authenticateStragglers (G:\workspace\realworld\cms\nodercms\nodercms\node_modules\mongoose\node_modules\mongodb-core\lib\connection\pool.js:443:16)
    at Connection.messageHandler (G:\workspace\realworld\cms\nodercms\nodercms\node_modules\mongoose\node_modules\mongodb-core\lib\connection\pool.js:477:5)
    at Socket.<anonymous> (G:\workspace\realworld\cms\nodercms\nodercms\node_modules\mongoose\node_modules\mongodb-core\lib\connection\connection.js:331:22)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by wugy0103** [comment]
这是来自QQ邮箱的自动回复邮件。
